const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORAGE='nvqs_td_github_v1';
let state={book:null,marks:{},filter:'all'};
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE)||'null');if(x&&typeof x==='object')state={...state,...x}}catch{}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function norm(s=''){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[đĐ]/g,'d').toLowerCase().trim()}
function collectorForThon(thon=''){const n=norm(thon);if(n.includes('bu lu'))return 'Điểu Gia Rưng';if(n.includes('dak con'))return 'Dương Trung Thủy';if(n.includes('dak mai'))return 'Điểu Bảy';return ''}
function fmtTime(x){if(!x)return '';const d=new Date(x);return Number.isNaN(+d)?'':d.toLocaleString('vi-VN',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit',year:'numeric'})}
function toast(msg,err=false){const t=$('#toast');t.textContent=msg;t.className='toast'+(err?' err':'');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.add('hidden'),2200)}
function validateBook(x){return x&&x.format==='NVQS_DECISION_ONLINE_ROSTER_V1'&&x.batchId&&Array.isArray(x.citizens)&&x.citizens.length>0}
function resultObj(){const b=state.book,now=new Date().toISOString();return {format:'NVQS_DECISION_RESULT_V2',snapshot:true,batchId:b.batchId,thon:b.thon||'',collector:collectorForThon(b.thon),sourceExportedAt:b.exportedAt||'',exportedAt:now,roster:b.citizens.map(c=>({id:c.id,maHoSo:c.maHoSo||'',hoTen:c.hoTen||''})),received:b.citizens.filter(c=>c.alreadyReceived||state.marks[c.id]).map(c=>({id:c.id,maHoSo:c.maHoSo||'',hoTen:c.hoTen||'',receivedAt:c.alreadyReceived?(c.receivedAt||b.exportedAt||now):(state.marks[c.id]?.at||now),preexisting:!!c.alreadyReceived}))}}
function resultFile(){const b=state.book,d=resultObj(),safe=(b.thon||'THON').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'_');return {name:`KET_QUA_PHAT_QD_${safe}_${new Date().toISOString().slice(0,10)}.json`,blob:new Blob([JSON.stringify(d,null,2)],{type:'application/json'})}}
function download(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function counts(){const b=state.book;if(!b)return {total:0,done:0,left:0};const done=b.citizens.filter(c=>c.alreadyReceived||state.marks[c.id]).length;return {total:b.citizens.length,done,left:b.citizens.length-done}}
function render(){const b=state.book;$('#emptyState').classList.toggle('hidden',!!b);$('#app').classList.toggle('hidden',!b);$('#stickySend').classList.toggle('hidden',!b);if(!b)return;$('#thonName').textContent=b.thon||'Không rõ thôn/tổ';$('#batchInfo').textContent='Mã sổ: '+b.batchId+' · Xuất: '+(fmtTime(b.exportedAt)||'—');const c=counts();$('#stTotal').textContent=c.total;$('#stDone').textContent=c.done;$('#stLeft').textContent=c.left;$('#progressText').textContent=`Đã phát ${c.done}/${c.total}`;const collector=collectorForThon(b.thon);$('#collectorName').textContent=collector||'Chưa thiết lập';$$('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===state.filter));drawPeople()}
function drawPeople(){const b=state.book;if(!b)return;const q=norm($('#q').value),f=state.filter,searching=!!q;let arr=b.citizens.filter(c=>{const done=!!c.alreadyReceived||!!state.marks[c.id];if(q&&!norm([c.hoTen,c.maHoSo,c.diaChi,c.ngaySinh].join(' ')).includes(q))return false;/* Khi đang tìm tên, giữ người vừa tích lại trên màn hình để TĐT thấy trạng thái đã đổi. */if(!searching){if(f==='pending'&&done)return false;if(f==='done'&&!done)return false}return true});arr.sort((a,b)=>Number(!!a.alreadyReceived||!!state.marks[a.id])-Number(!!b.alreadyReceived||!!state.marks[b.id])||String(a.hoTen||'').localeCompare(String(b.hoTen||''),'vi'));
$('#people').innerHTML=arr.map(c=>{const locked=!!c.alreadyReceived,done=locked||!!state.marks[c.id],at=locked?(c.receivedAt||state.book.exportedAt):(state.marks[c.id]?.at||'');const label=locked?'ĐÃ NHẬN':'ĐÃ PHÁT';return `<article class="person ${done?'done':''} ${locked?'locked':''}" data-id="${esc(c.id)}" ${locked?'data-locked="1"':''}><div class="person-info"><div class="person-name">${esc(c.hoTen||'Không tên')}</div><div class="person-meta">${esc(c.diaChi||c.maHoSo||'Chưa có địa chỉ')}</div>${done&&at?`<div class="person-time">${locked?'Đã nhận trước':'Đã phát'} · ${esc(fmtTime(at))}</div>`:''}</div><div class="status check-status ${done?'done':''} ${locked?'locked':''}" role="checkbox" aria-checked="${done?'true':'false'}" aria-label="${label}"><span class="check-square" aria-hidden="true">${done?'✓':''}</span><span class="check-label">${label}</span></div></article>`}).join('')||'<div class="empty-list">Không có người phù hợp.</div>';
$$('.person:not(.locked)').forEach(row=>row.onclick=()=>toggle(row.dataset.id))}
function refreshAfterToggle(){const c=counts();$('#stTotal').textContent=c.total;$('#stDone').textContent=c.done;$('#stLeft').textContent=c.left;$('#progressText').textContent=`Đã phát ${c.done}/${c.total}`;drawPeople()}
function toggle(id){const b=state.book,c=b.citizens.find(x=>String(x.id)===String(id));if(!c||c.alreadyReceived)return;const qEl=$('#q');if(state.marks[id])delete state.marks[id];else state.marks[id]={at:new Date().toISOString()};save();/* Sau khi tích xong, tự xóa ô tìm kiếm và đưa con trỏ trở lại để nhập tên người tiếp theo. */qEl.value='';refreshAfterToggle();requestAnimationFrame(()=>{qEl.focus({preventScroll:true});qEl.setSelectionRange(qEl.value.length,qEl.value.length)});toast(state.marks[id]?'Đã đánh dấu ĐÃ PHÁT · Có thể nhập tên tiếp theo':'Đã chuyển về CHƯA PHÁT · Có thể nhập tên tiếp theo')}
async function importRoster(file){let x;try{x=JSON.parse(await file.text())}catch{return toast('Không đọc được file danh sách',true)}if(!validateBook(x))return toast('File không đúng định dạng NVQS',true);const same=state.book&&state.book.batchId===x.batchId,oldMarks=same?state.marks:{};const ids=new Set(x.citizens.map(c=>String(c.id)));state.book={format:x.format,batchId:String(x.batchId),thon:String(x.thon||''),exportedAt:String(x.exportedAt||''),citizens:x.citizens.filter(c=>c&&c.id&&c.hoTen).map(c=>({id:String(c.id),maHoSo:String(c.maHoSo||''),hoTen:String(c.hoTen||''),ngaySinh:String(c.ngaySinh||''),diaChi:String(c.diaChi||''),alreadyReceived:!!c.alreadyReceived,receivedAt:String(c.receivedAt||'')}))};state.marks={};for(const [id,v] of Object.entries(oldMarks))if(ids.has(String(id)))state.marks[id]=v;state.filter='pending';save();$('#q').value='';render();toast(`Đã mở sổ ${state.book.thon||''} · ${state.book.citizens.length} người`)}
async function restoreResult(file){if(!state.book)return toast('Hãy nạp danh sách trước',true);let x;try{x=JSON.parse(await file.text())}catch{return toast('Không đọc được file kết quả',true)}if(x?.format!=='NVQS_DECISION_RESULT_V2'||x.batchId!==state.book.batchId||!Array.isArray(x.received))return toast('File kết quả không thuộc sổ này',true);const received=new Map(x.received.map(r=>[String(r.id),r]));const newMarks={};for(const c of state.book.citizens){if(c.alreadyReceived)continue;const r=received.get(String(c.id));if(r)newMarks[c.id]={at:r.receivedAt||x.exportedAt||new Date().toISOString()}}state.marks=newMarks;save();render();toast('Đã khôi phục tiến độ')}
$('#rosterFile').onchange=async e=>{const f=e.target.files?.[0];if(f)await importRoster(f);e.target.value=''};
$('#restoreFile').onchange=async e=>{const f=e.target.files?.[0];if(f)await restoreResult(f);e.target.value=''};
$('#q').oninput=drawPeople;
$$('.filter').forEach(btn=>btn.onclick=()=>{state.filter=btn.dataset.filter;save();render()});
$('#changeBookBtn').onclick=()=>$('#rosterFile').click();
$('#downloadBtn').onclick=()=>{if(!state.book)return;const f=resultFile();download(f.name,f.blob);toast('Đã tải file dự phòng')};
$('#shareBtn').onclick=async()=>{if(!state.book)return;const f=resultFile();const file=new File([f.blob],f.name,{type:'application/json'});try{if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({title:'Kết quả phát Quyết định NVQS',text:`${state.book.thon||''} · ${counts().done}/${counts().total} đã phát`,files:[file]});return}download(f.name,f.blob);toast('Đã tải file. Gửi file này cho BCHQS qua Zalo.')}catch(e){if(e?.name!=='AbortError'){download(f.name,f.blob);toast('Đã tải file để gửi qua Zalo.')}}};
function updateNet(){const el=$('#netBadge');el.textContent=navigator.onLine?'ONLINE':'OFFLINE';el.classList.toggle('offline',!navigator.onLine)}
addEventListener('online',updateNet);addEventListener('offline',updateNet);updateNet();
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
load();render();
